
export const ACTION_TYPE_AUTH = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
}
export const ACTION_TYPE_USER = {
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_DOING: "GET_PROFILE_DOING",
  GET_PROFILE_FAILED: "GET_PROFILE_FAILED",

  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILED: "UPDATE_PROFILE_FAILED",

  GET_ALL_USER_DOING: "GET_ALL_USER_DOING",
  GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",
  GET_ALL_USER_FAILED: "GET_ALL_USER_FAILED"
}
