
export const ACTION_TYPE_AUTH = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
}
export const ACTION_TYPE_USER = {
  GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
  GET_USER_PROFILE_DOING: "GET_USER_PROFILE_DOING",
  GET_USER_PROFILE_FAILED: "GET_USER_PROFILE_FAILED",

  UPDATE_USER_PROFILE_SUCCESS: "UPDATE_USER_PROFILE_SUCCESS",
  UPDATE_USER_PROFILE_FAILED: "UPDATE_USER_PROFILE_FAILED",

  GET_ALL_USER_DOING: "GET_ALL_USER_DOING",
  GET_ALL_USER_SUCCESS: "GET_ALL_USER_SUCCESS",
  GET_ALL_USER_FAILED: "GET_ALL_USER_FAILED"
}
export const ACTION_TYPE_CHAT = {
  ADD_MESSAGE_SUCCESS: "ADD_MESSAGE_SUCCESS",
  ADD_MESSAGE_FAILED: "ADD_MESSAGE_FAILED",
  SET_CURRENT_ROOMID: "SET_CURRENT_ROOMID",
  FETCH_MESSAGE_HISTORY: "FETCH_MESSAGE_HISTORY",
}
export const ACTION_TYPE_FRIEND = {
  GET_FRIEND_PROFILE_DOING: "GET_FRIEND_PROFILE_DOING",
  GET_FRIEND_PROFILE_SUCCESS: "GET_FRIEND_PROFILE_SUCCESS"
}